# Code 2: Perceptron

## Part 1: Scikit-Learn Overview
Scikit-Learn uses the same design principles across its API. This is a brief overview of the format. 

### Consistency
All objects share a consistent and simple interface.

### Estimators
Any object that estimates parameters based on a dataset is called an *estimator*. The estimation is done by the *fit( )* method which takes a dataset (and labels for a supervised algorithm) as a parameter. All other parameters used to guide the estimation are called *hyperparameters*, and these are set as instance variables via a constructor parameter. 

### Transformers
Estimators that can also transform the dataset are called *transformers* (not to be confused with the newest Neural Net Transformer). This is done with the *transform( )* method on the dataset. All transformers also have the *fit_transform( )* method: this is equivalent to calling fit( ) and then transform( ), but is usually optimized to run faster. 

### Predictors
Estimators that are given a dataset and can make predictions on it are called *predictors*. This is done with the *predict( )* method which takes a dataset and returns corresponding predictions. These also have a *score( )* method that measures the quality of the predictions using a test set (and corresponding labels if supervised). 

### Inspection
All the estimator's hyperparameters are accesible through public instance variables (e.g., imputer.strategy) and its learned parameters are accessible through public instance variables with an underscore suffix (e.g., imputer.statistics_). 

### Use of other packages
Scikit-Learn uses other packages rather than create its own classes. Datasets are represented as NumPy arrays or SciPy matrices. Hyperparameters are Python strings or numbers. 

### Default Parameters
Scikit-Learn starts with typical default values for most parameters. 

## Part 2: Basic Perceptron
Let's code a perceptron using Scikit-Learn!
Your job is to consult the Scikit-Learn API and fill in the skeleton code. 

In [1]:
# imports
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

In [2]:
# Load the iris dataset
# It consists of 3 different types of irises’ (Setosa, Versicolour, & Virginica) 
#     petal & sepal length, stored in a 150x4 numpy.ndarray.
#     Rows: samples 
#     Columns: Sepal Length, Sepal Width, Petal Length & Petal Width.
iris = load_iris()


In [3]:
# Split the dataset into X (features) and y (labels)
# X: should contain all rows, but only the petal length & petal width features
X = iris.data[: , [2,3]]

# y: Setosa is our target
y = iris.target


print(X)
print(y)


[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [11]:
# Create an instance of a Perceptron classifier
per_clf = Perceptron()
print(X, y)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [12]:
# Use the Perceptron's fit method on your smaller dataset
per_clf.fit(X, y)
#per_clf.transform(X, y)

Perceptron()

In [13]:
# Use the Perceptron's predict method on sample[2,0.5]
y_pred = per_clf.predict([[2,0.5]])

print(y_pred)

[0]


## Part 3: Another Perceptron

In [9]:
# import Scikit-Learn's StandardScaler, train_test_split, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [49]:
# Save the iris dataset data and target values to X and y, respectively
X = iris.data[: , [0,1,2,3]]
y = iris.target

In [50]:
# Print/view the first 5 observations from y
y[:6]

array([0, 0, 0, 0, 0, 0])

In [51]:
# Print/view the first 10 observations of X
X[:11]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2]])

In [59]:
# Split the dataset into 80% training and 20% testing
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)
y_train, y_test = train_test_split(y, test_size=0.2, random_state=42)

In [65]:
from sklearn.preprocessing import StandardScaler

# Train the StandardScaler to format the X training set
# Remember StandardScaler standardizes all features to have
#     mean = 0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [66]:
# Apply the StandardScaler to the X training dataset
X_train_std = sc.transform(X_train)

# Apply StandardScaler to X test data
X_test_std = sc.transform(X_test)


In [72]:
# Create a Perceptron object with parameters:
#     50 iterations (epochs) over the dataset
#     learning rate n = 0.1
#     random_state = 0
per = Perceptron(max_iter = 50, alpha = 0.1,random_state=  0)

# Train the Perceptron on the standardized X training set
per.fit(X_train_std, y_train)

Perceptron(alpha=0.1, max_iter=50)

In [75]:
# Apply trained Perceptron on standardized X test dataset to make predictions for y
y_pred = per.predict(sc.transform(X_test))

# Print predictions
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [76]:
# Print true labels

print (y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [88]:
# Print the accuracy_score of the model 
# You should compare the actual labels with the predicted labels
count = 0
for i in range(len(y_pred)):
    if y_pred[i] == y_test[i]:
        count +=1
print("Accuracy: {}".format(count/len(y_pred) * 100))

Accuracy: 96.66666666666667
